version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: t_app_1
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - t_network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: t_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - t_network
    depends_on:
      - app

  db:
    image: postgres:16-alpine
    container_name: t_app_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-t_app}
      POSTGRES_USER: ${DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - t_network

networks:
  t_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local